language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
    
install:
 - composer self-update
 - composer global require hirak/prestissimo
 - composer install --no-interaction
before_script:
  - mkdir -p build/
  - mkdir -p build/logs
script:
 - find src/ -name '*.php' -print0 | xargs -0 -L 1 php -l
 - find tests/ -name '*.php' -print0 | xargs -0 -L 1 php -l
 - phpunit
after_script:
 - php vendor/bin/php-coveralls -v
 - php vendor/bin/codacycoverage clover build/logs/clover.xml
