<?php

namespace Phramework\Validate;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-05 at 22:11:07.
 */
class BaseValidatorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Boolean
     */
    protected $bool;
    protected $int;
    protected $str;
    protected $uint;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->bool = new BooleanValidator();
        $this->int = new IntegerValidator();
        $this->str = new StringValidator();
        //$this->uint = new new UnsignedIntegerValidator(;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Phramework\Validate\BaseValidator::parseStatic
     */
    public function testParseStatic()
    {
        $this->assertSame(
            5,
            IntegerValidator::parseStatic('5'),
            'Expect to convert 5 to integer'
        );

        $this->assertSame(
            5.5,
            NumberValidator::parseStatic('5.5')
        );

        $o = ObjectValidator::parseStatic(['ok' => true]);

        $this->assertInternalType('object', $o);
        $this->assertObjectHasAttribute('ok', $o);
        $this->assertSame(true, $o->ok);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::createFromJSON
     */
    public function testCreateFromJSON()
    {
        $json = '{
            "type": "integer",
            "minimum" : -1000,
            "maximum" : 1000
        }';

        $validationObject = IntegerValidator::createFromJSON($json);

        $this->assertInstanceOf(BaseValidator::class, $validationObject);

        $this->assertSame(
            -1000,
            $validationObject->minimum
        );
    }

    /**
     * @covers Phramework\Validate\BaseValidator::createFromJSON
     */
    public function testCreateFromJSON2()
    {
        $json = '{
            "type": "unsignedinteger",
            "minimum" : -1000,
            "maximum" : 1000
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(BaseValidator::class, $validationObject);
        $this->assertInstanceOf(UnsignedIntegerValidator::class, $validationObject);

        $this->assertSame(
            -1000,
            $validationObject->minimum
        );
    }

    /**
     * @covers Phramework\Validate\BaseValidator::createFromJSON
     */
    public function testCreateFromJSON3()
    {
        $json = '
        {
          "type": "object",
          "properties": {
            "data": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "enum",
                  "enum": ["user"]
                },
                "order": {
                  "type": "unsignedinteger",
                  "default" : 0
                }
              },
              "required": ["type"]
            }
          }
        }';

        $validationObject = ObjectValidator::createFromJSON($json);

        $this->assertInstanceOf(ObjectValidator::class, $validationObject);
        $this->assertInternalType(
            'object',
            $validationObject->properties
        );
        $this->assertInstanceOf(
            ObjectValidator::class,
            $validationObject->properties->data
        );

        $data = $validationObject->properties->data;

        $this->assertInstanceOf(
            EnumValidator::class,
            $data->properties->type
        );

        $this->assertInstanceOf(
            UnsignedIntegerValidator::class,
            $data->properties->order
        );
        $this->assertInternalType(
            'array',
            $data->properties->type->enum
        );

        $this->assertSame(
            0,
            $data->properties->order->default
        );
    }


    /**
     * @covers Phramework\Validate\BaseValidator::createFromJSON
     * @expectedException Exception
     */
    public function testCreateFromJSONFailure()
    {
        $json = '{
            "type": "xyz",
            "minimum" : -1000,
            "maximum" : 1000
        }';

        $validationObject = IntegerValidator::createFromJSON($json);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::parse
     */
    public function testParseSuccess()
    {
        $input = [
            'weight' => '5',
            'obj' => [
                'valid' => 'true',
                'number' => 10.2,
            ]
        ];

        $validationObject = new ObjectValidator(
            [ //properties
                'weight' => new IntegerValidator(-10, 10, true),
                'obj' => new ObjectValidator(
                    [ //properties
                        'valid' => new BooleanValidator(),
                        'number' => new NumberValidator(0, 100),
                        'not_required' => (new NumberValidator(0, 100))->setDefault(5.5),
                    ],
                    ['valid'] //required
                )
            ],
            ['weight'] //required
        );

        $record = $validationObject->parse($input);
        $this->assertInternalType('object', $record);
        $this->assertInternalType('object', $record->obj);
        $this->assertInternalType('float', $record->obj->not_required);
        $this->assertEquals(5, $record->weight);
        $this->assertTrue($record->obj->valid);
        $this->assertEquals(5.5, $record->obj->not_required);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::parse
     */
    public function testParseSuccess2()
    {
        $input = '5';

        $validationModel = new IntegerValidator(0, 6);

        $cleanInput = $validationModel->parse($input);

        $this->assertInternalType('integer', $cleanInput);
        $this->assertEquals(5, $cleanInput);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::parse
     * @expectedException Exception
     * @todo \Phramework\Exceptions\MissingParametersException
     */
    public function testParseFailure()
    {
        $input = [
            'weight' => '5',
            'obj' => [
                //'valid' => 'true',
                'number' => 10.2,
            ]
        ];

        $validationObject = new ObjectValidator(
            [ //properties
                'weight' => new IntegerValidator(-10, 10, true),
                'obj' => new ObjectValidator(
                    [ //properties
                        'valid' => new BooleanValidator(),
                        'number' => new NumberValidator(0, 100),
                        'not_required' => (new NumberValidator(0, 100))->setDefault(5.5),
                    ],
                    ['valid'] //required
                )
            ],
            ['weight'] //required
        );

        $record = $validationObject->parse($input);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::parse
     * @expectedException Exception
     * @todo \Phramework\Exceptions\IncorrectParametersException
     */
    public function testParseFailure2()
    {
        $input = [
            'weight' => '555', //out of range
            'obj' => [
                'valid' => 'ΝΟΤ_VALID',
                'number' => 10.2
            ]
        ];

        $validationObject = new ObjectValidator(
            [ //properties
                'weight' => new IntegerValidator(-10, 10, true),
                'obj' => new ObjectValidator(
                    [ //properties
                        'valid' => new BooleanValidator(),
                        'number' => new NumberValidator(0, 100),
                        'not_required' => (new NumberValidator(0, 100))
                            ->setDefault(5),
                    ],
                    ['valid'] //required
                )
            ],
            ['weight'] //required
        );

        $record = $validationObject->parse($input);

    }

    /**
     * Validate against common enum keyword
     * @covers Phramework\Validate\BaseValidator::validateCommon
     * @covers Phramework\Validate\BaseValidator::validateEnum
     */
    public function testValidateCommon()
    {
        $validator = (new IntegerValidator(0, 10));

        $validator->enum = [1, 3, 5];

        $return = $validator->validate(1);
        $this->assertTrue(
            $return->status,
            'Expect true since "1" is in enum array'
        );

        $return = $validator->validate(2);
        $this->assertFalse(
            $return->status,
            'Expect false since "2" is not in enum array'
        );
    }

    /**
     * Validate against common enum keyword
     * @covers Phramework\Validate\BaseValidator::validateEnum
     */
    public function testValidateEnum()
    {
        $validator = (new IntegerValidator(0, 10));

        $validator->enum = [1, 3, 5];

        $return = $validator->validate(1);

        $this->assertTrue(
            $return->status,
            'Expect true since "1" is in enum array'
        );

        $return = $validator->validate(2);
        $this->assertFalse(
            $return->status,
            'Expect false since "2" is not in enum array'
        );
    }

    /**
     * Validate against common enum keyword,
     * expect exception sice objects and arrays are not yet supported for enum keyword
     * @expectedException Exception
     * @covers Phramework\Validate\BaseValidator::validateEnum
     */
    public function testValidateEnumException()
    {
        $validator = (new ArrayValidator());

        $validator->enum = [[1], [1,2]];

        $validator->validate([1]);
    }

    /**
     * Validate against common enum keyword,
     * expect exception sice objects and arrays are not yet supported for enum keyword
     * @expectedException Exception
     * @covers Phramework\Validate\BaseValidator::validateEnum
     */
    public function testValidateEnumException2()
    {
        $validator = (new IntegerValidator(0, 10));

        $validator->enum = [[1], new \stdClass(), 5];

        $validator->validate(2);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::parse
     * @expectedException Exception
     */
    public function testParseFailure3()
    {
        $input = '87';

        $validationModel = new IntegerValidator(0, 6);

        $cleanInput = $validationModel->parse($input);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::__get
     */
    public function testGetType()
    {
        $validator = new IntegerValidator();
        $this->assertEquals('integer', $validator->type);
    }

    /**
     * @covers Phramework\Validate\BaseValidator::getType
     */
    public function testGetType2()
    {
        $validator = new IntegerValidator();
        $this->assertEquals('integer', $validator->getType());
    }

    /**
     * @covers Phramework\Validate\BaseValidator::__get
     * @expectedException Exception
     */
    public function testGet()
    {
        $validator = new IntegerValidator();
        $validator->IM_SURE_THIS_CANT_BE_FOUND;
    }

    /**
     * @covers Phramework\Validate\BaseValidator::__set
     * @expectedException Exception
     */
    public function testSetFailure()
    {
        $validator = new IntegerValidator();
        $validator->IM_SURE_THIS_CANT_BE_FOUND = 'value';
    }

    /**
     * @covers Phramework\Validate\BaseValidator::__set
     */
    public function testSetSuccess()
    {
        $validator = new IntegerValidator();
        $validator->title = 'my title';

        $this->assertSame(
            $validator->title,
            'my title'
        );

        $returnValue = $validator->__set('title', 'my title');

        $this->assertInstanceOf(
            IntegerValidator::class,
            $returnValue
        );
    }

    /**
     * @covers Phramework\Validate\BaseValidator::setEnum
     */
    public function testSetEnum()
    {
        $validator = new IntegerValidator();

        $enum = [1, 2, 3];

        $returnValue = $validator->setEnum($enum);

        $this->assertSame(
            $validator->enum,
            $enum
        );

        $this->assertInstanceOf(
            IntegerValidator::class,
            $returnValue
        );

        $return = $validator->validate(4);

        $this->assertFalse(
            $return->status,
            'Expect true since "4" is not in enum array'
        );
    }
}
