<?php

namespace Phramework\Validate;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 22:11:07.
 */
class StringWithDatetimeFormatValidatorTest extends TestCase
{

    /**
     * @var String
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new StringValidator(
            20,
            35,
            null,
            false,
            'date-time'
        );
    }

    public function validateSuccessProvider()
    {
        //input, expected
        return [
            ['2019-11-14T14:30:26+02:00', '2019-11-14T14:30:26+02:00'],
            ['2019-11-14T14:30:60+02:00', '2019-11-14T14:30:60+02:00'],
            ['2019-11-14T14:30:26Z', '2019-11-14T14:30:26Z'],
        ];
    }

    public function validateFailureProvider()
    {
        //input
        return [
            ['2019-11-14T14:30:26Z+02:00', 'pattern'],
            ['2019-11-14T', 'pattern'],
            ['2019-11-14 14:30:26+02:00', 'pattern'],
            ['2019-11-14T14:30:26+02:00random', 'pattern'],
            ['2019-11-14T14:30:26.123543333+02:00', 'maxLength'],
        ];
    }

    /**
     * @dataProvider validateSuccessProvider
     */
    public function testValidateSuccess($input, $expected)
    {
        $return = $this->object->validate($input);

        $this->assertInternalType('string', $return->value);
        $this->assertEquals($expected, $return->value);
        $this->assertTrue($return->status);
    }

    /**
     * @dataProvider validateFailureProvider
     */
    public function testValidateFailure($input)
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    public function testGetType()
    {
        $this->assertEquals('string', $this->object->getType());
    }

    public function testDatetimeFormat()
    {
        $this->assertEquals('date-time', $this->object->getFormat());
    }
}
