<?php

namespace Phramework\Validate;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015 - 2016-10-05 at 20:04:03.
 */
class UnsignedIntegerValidatorTest extends TestCase
{

    /**
     * @var UnsignedIntegerValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UnsignedIntegerValidator(10, 1000, true);
    }

    public function validateSuccessProvider()
    {
        //input, expected
        return [
            ['100', 100],
            [124, 124]
        ];
    }

    public function validateFailureProvider()
    {
        //input
        return [
            ['-0x'],
            ['abc'],
            ['+xyz']
            [-1000],
            ['-4'],
            [4], //because of min,
            [1.4],
            [-13.5]
        ];
    }

    public function testConstruct()
    {
        $validator = new UnsignedIntegerValidator(
            0,
            1
        );
    }

    /**
     * @expectedException \Exception
     */
    public function testConstructFailure()
    {
        $validator = new UnsignedIntegerValidator(
            -1
        );
    }

    /**
     * Helper method
     */
    private function validateSuccess(UnsignedIntegerValidator $object, $input, $expected)
    {
        $return = $object->validate($input);

        $this->assertTrue($return->status);
        $this->assertInternalType('integer', $return->value);
        $this->assertSame($expected, $return->value);
    }

    /**
     * @dataProvider validateSuccessProvider
     */
    public function testValidateSuccess($input, $expected)
    {
        $this->validateSuccess($this->object, $input, $expected);
    }

    public function testCreateFromJSON()
    {
        $json = '{
            "type": "unsignedinteger"
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(UnsignedIntegerValidator::class, $validationObject);
    }

    public function testCreateFromJSONAlias()
    {
        $json = '{
            "type": "uint"
        }';

        $validationObject = BaseValidator::createFromJSON($json);

        $this->assertInstanceOf(UnsignedIntegerValidator::class, $validationObject);
    }

    public function testGetType()
    {
        $this->assertEquals('unsignedinteger', $this->object->getType());
    }
}
